#!/bin/bash

if [ "$1" == "run" ]; then
    go build -o aseli-api && ./aseli-api
elif [ "$1" == "start" ]; then
    go build -o aseli-api && ./aseli-api
elif [ "$1" == "generate" ]; then
    go get github.com/99designs/gqlgen && go run github.com/99designs/gqlgen generate
elif [ "$1" == "database" ]; then
    surreal start file://./SurrealDB
elif [ "$1" == "db" ]; then
    surreal start file://./SurrealDB
else
    echo "Command not found."
fi
