package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"aseli-api/graph/helper"
	"aseli-api/graph/model"
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"golang.org/x/exp/slices"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, title string, description string, image graphql.Upload) (*model.ResponseCreatePost, error) {
	if !slices.Contains([]string{"image/png", "image/jpeg"}, image.ContentType) {
		return nil, fmt.Errorf("File is not an image.")
	}

	helper.Post.SaveImage(helper.Post{}, image)
	
	return &model.ResponseCreatePost{
		PostID: "sigma",
	}, nil
}
