scalar Upload

type Post {
    id: String
    user: String!
    title: String!
    description: String!
    image: String! 
    ril: [String!]!
    fek: [String!]!
}

type PostResponse {
    id: String
    username: String!
    title: String!
    description: String!
    image: String!
    ril: Int!
    fek: Int!
}

type responseCreatePost {
    post_id: String!
}

extend type Query {
    posts: [PostResponse!]!
}

extend type Mutation {
    createPost(
        title: String!
        description: String!
        image: Upload!
    ): responseCreatePost!
    sendRil(post_id: String!): Boolean
    sendFek(post_id: String!): Boolean
}