scalar Upload

type Post {
    id: String
    user: String!
    title: String!
    description: String!
    image: String!
}

type responseCreatePost {
    post_id: String!
}

# extend type Query {`

# }

extend type Mutation {
    createPost(
        title: String!
        description: String!
        image: Upload!
    ): responseCreatePost!
}