type User {
    id: String
    username: String!
    password: String!
}

type UserResponse {
    id: String!
    username: String!
}

# Register
input registerRequest {
    username: String!
    password: String!
    verification_password: String!
}

type registerResponse {
    success: Boolean!
    id: String
}

# Login
input loginRequest {
    username: String!
    password: String!
}

type loginResponse {
    success: Boolean!
    id: String
}

type Query {
    users: [UserResponse!]!
    getUser(id: String!): UserResponse!
}

type Mutation {
    registerUser(input: registerRequest!): registerResponse!
    loginUser(input: loginRequest!): loginResponse!
}