type User {
    id: String!
    username: String!
}

input newUser {
    username: String!
    password: String!
}

type Query {
    users: [User!]!
    getUser(id: String): User!
}

type Mutation {
    registerUser(input: newUser): User!
}